### ISSUE TITLE
You are absurdly talented

### ISSUE THREAD

**Issue by GavinRay97** [mrkuz/hello-kotlin#1]
I stumbled on this after finding your `kradle` plugin listed on Gradle plugins list, and then browsing your repos (since that plugin seemed well-thought-out).

Opening the main HTTP server file, I saw the use of dependency injection and DSL-style endpoints -- but no library imports?!

Then I slowly started to realize that everything, from the DI, to the HTTP lib, etc, had been hand-written.
In clean/beautiful, well-documented code.

Stunning.

**Comment by mrkuz** [comment]
Thanks!

Building everything from scratch was a great way to explore the features of Kotlin. The language makes writing readable and compact code a breeze. I was impressed how much you can archive with just a few lines.
